### PR TITLE
Typo in the readme

### PR DESCRIPTION
**Pull request by enricotoi**
There is a typo in the "Run Simulation Demo" part of the readme.md

It says to "roslaunch ros_control_boilerplate rrbot_simulaton.launch" where as the launch file is name "rrbot_simulation.launch" so the current instruction is missing and "i" in the name of the launch file

### CODE REVIEW

**Comment by davetcoleman** [comment]
This PR is merging the wrong branches - it is attempting to merge two branches from this repo but you meant to propose your own branch. Please try again.

**Comment by enricotoi** [comment]
The only branches I can create a pull request with are ones that can compare each other. And the only ones on the list that I can choose from that do compare each other are these different ros distro devel branches. I don't have any branches of my own.

**Comment by davetcoleman** [comment]
Did you fork this repo and create a PR using a branch from your fork? This current pull request is simply wrong.

**Comment by enricotoi** [comment]
Hadn't heard of forking before, so nope hadn't done that.

**Comment by davetcoleman** [comment]
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Pull request closed without merging**
